version: 2

defaults: &defaults
  working_directory: ~/repository
  docker:
    - image: circleci/node:14

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run: npm i

  test-cov:
    <<: *defaults
    steps:
      - run: npm run test:cover
      - run:
         name: report coverage stats for non-PRs
         command: |
           if [[ -z $CI_PULL_REQUEST ]]; then
             ./node_modules/.bin/codecov
           fi

  build:
    <<: *defaults
    steps:
    - run: npm run build

workflows:
  version: 2
  install-and-parallel-test:
    jobs:
      - install
      - test-cov:
          requires:
            - install
      - build:
          requires:
            - install
            - test-cov

