version: 2

defaults: &defaults
  working_directory: ~/repository
  docker:
    - image: circleci/node:14

jobs:
  test-cov:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run test:cover
      - run:
         name: report coverage stats for non-PRs
         command: |
           if [[ -z $CI_PULL_REQUEST ]]; then
             ./node_modules/.bin/codecov
           fi
  build:
    <<: *defaults
    steps:
    - checkout
    - run: npm i
    - run: npm run build
