version: 2

defaults: &defaults
  working_directory: ~/repository
  docker:
    - image: circleci/node:14

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run: npm i

  test-cov:
    <<: *defaults
    steps:
      - run: npm run test:cover

  build:
    <<: *defaults
    steps:
    - run: npm run build

workflows:
  version: 2
  install-test-and-build:
    jobs:
      - install
      - test-cov:
          requires:
            - install
      - build:
          requires:
            - install
            - test-cov

