version: 2

defaults: &defaults
  working_directory: ~/repository
  docker:
    - image: circleci/node:14

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - persist_to_workspace:
          root: ~/project

  test-cov:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run test:cover

  build:
    <<: *defaults
    steps:
    - attach_workspace:
        at: ~/project
    - run: npm run build

workflows:
  version: 2
  install-and-parallel-test:
    jobs:
      - install
      - test-cov:
          requires:
            - install
      - build:
          requires:
            - install
            - test-cov

